version: 0.0
os: linux
files:
  - source: /
    destination: /opt/bitnami/projects/SCUP
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: deploy_scripts/pre_deploy.py
      timeout: 6000
      runas: bitnami

  AfterInstall:
    - location: deploy_scripts/post_deploy.py
      timeout: 6000
      runas: bitnami

  ApplicationStart:
    - location: deploy_scripts/ctlscript.py start
      timeout: 6000
      runas: bitnami
  
  ApplicationStop:
    - location: deploy_scripts/ctlscript.py stop
      timeout: 6000
      runas: bitnami