# Generated by Django 4.1.3 on 2023-06-04 06:23

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectivespage',
            name='Section_1',
            field=wagtail.fields.RichTextField(default='Default value for Section_1'),
        ),
        migrations.AlterField(
            model_name='objectivespage',
            name='about',
            field=wagtail.fields.RichTextField(default='Default value for about'),
        ),
        migrations.AlterField(
            model_name='objectivespage',
            name='team',
            field=wagtail.fields.RichTextField(default='Default value for team'),
        ),
    ]
