# Generated by Django 4.1.3 on 2023-06-04 06:28

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0002_alter_objectivespage_section_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectivespage',
            name='about',
            field=wagtail.fields.RichTextField(default='<strong>Default header for about</strong><br>Default value for about'),
        ),
        migrations.AlterField(
            model_name='objectivespage',
            name='team',
            field=wagtail.fields.RichTextField(default='<strong>Default header for about</strong><br>Default value for about'),
        ),
    ]
