###############################################################################
# Constructs a new SCUP instance. Note this YAML only creates the Lightsail
# instance and NOT any of the other infrastructure (ex: CodeDeploy, CodePipeline,
# etc.)
###############################################################################

Description: Deploys a new SCUP instance.

Parameters:

  DeployEnvironment:
    Type: String
    Description: Environment to build for - one of prod, test, or dev
    Default: 'prod'
    AllowedPattern: "^(prod|test|dev)$"

Resources:
SCUP:
    Type: AWS::Lightsail::Instance
    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: PT5M
    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              ruby:
                -
          files:
            /home/bitnami/install:
              source: !Join
                - ""
                - - "https://aws-codedeploy-"
                  - !Ref "AWS::Region"
                  - ".s3.amazonaws.com/latest/install"
              mode: 000755
          commands:
            00-install-agent:
              command: ./install auto
              cwd: /home/bitnami
            01-cfn-signal:
              command: !Join
                - ""
                - - "/opt/aws/bin/cfn-signal -e 0 --stack "
                  - !Ref "AWS::StackName"
    Properties:
      InstanceName: scup
      AvailabilityZone: us-east-1a
      BlueprintId: django_bitnami
      BundleId: small_3_0
      Networking:
        Ports:
          - CommonName: SSH
            Protocol: TCP
            FromPort: 22
            ToPort: 22
          - CommonName: HTTP
            Protocol: TCP
            FromPort: 80
            ToPort: 80
          - CommonName: HTTPS
            Protocol: TCP
            FromPort: 80
            ToPort: 80
      Tags:
        - Key: Environment
          Value: !Ref DeployEnvironment
        - Key: Name
          Value: scup
      UserData:
        !Join 
        - ""
        - - "#!/bin/bash\n"
          - "yum -y update\n"
          - "yum -y install cfn-bootstrap\n"
          - "/opt/aws/bin/cfn-init -v"
          - " --stack "
          - !Ref "AWS::StackName"
          - " --resource SCUP"
          - " --region "
          - !Ref "AWS::Region" 
          - "\n"