###############################################################################
# Creates all the required infrastructure for running a SCUP instance. The
# template is meant to be used as part of the CI/CD pipeline and can deploy
# new versions of SCUP as 'prod', 'test', or 'dev' environments.
#
# Important Notes:
#   1) The GitHub connection will be created in AWS from this template, but must
#      still be manually configured/authenticated before use. This can be done
#      by going to CodePipeline in the AWS console -> Settings (left-drawer) ->
#      Connections -> select scup-github-connection and follow any remaining
#      instructions
###############################################################################

Description: Deploys all infrastructure components required by SCUP.

Parameters:

  DeployEnvironment:
    Type: String
    Description: Environment to build for - one of prod, test, or dev
    Default: 'prod'
    AllowedPattern: "^(prod|test|dev)$"

Resources:

  GitHubConnection:
    Type: AWS::CodeStarConnections::Connection
    Properties:
      ConnectionName: scup-github-connection
      ProviderType: GitHub

  SCUPCodePipelineArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ["-", [scup, codepipeline, artifacts, !Ref DeployEnvironment]]

  SCUPCodeDeployArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ["-", [scup, codedeploy, artifacts, !Ref DeployEnvironment]]

  SCUPCodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Service role to be used with the SCUP CodePipeline
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "codepipeline.amazonaws.com"
            Action:
              - sts:AssumeRole
        Policies:
          - PolicyName: S3CodebuildAccess
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - s3:GetObject
                    - s3:GetObjectVersion
                    - s3:GetObjectVersioning
                    - s3:PutObject
                  Resource:
                    - !GetAtt SCUPCodePipelineArtifactsBucket.Arn
                    - !Sub ${SCUPCodePipelineArtifactsBucket.Arn}/*
                - Effect: Allow
                  Action:
                    - codebuild:BatchGetBuilds
                    - codebuild:StartBuild
                  Resource:
                    - "*"
                - Effect: Allow
                  Action:
                    - codestar-connections:UseConnection
                  Resource:
                    - !Ref GitHubConnection

  SCUPCodeDeployServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Service role to be used with the SCUP CodeDeploy
      AssumePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codedeploy.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole

  SCUPLightsailCodeDeployUsers:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Join ["-", [scup, lightsail, codedeploy, users, !Ref DeployEnvironment]]
      Policies:
        - PolicyName: CodeDeployLightsailPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                Resource:
                  - arn:aws:s3:::scup-*/*
                  - arn:aws:s3:::aws-codedeploy-us-east-2/*
                  - arn:aws:s3:::aws-codedeploy-us-east-1/*
                  - arn:aws:s3:::aws-codedeploy-us-west-2/*
                  - arn:aws:s3:::aws-codedeploy-us-west-1/*

  SCUPDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      DeploymentGroupName: !Join ["-", [scup, deployment, group, !Ref DeployEnvironment]]
      ApplicationName: !Join ["-", [scup, !Ref DeployEnvironment]]
      DeploymentStyle:
        DeploymentType: IN_PLACE
        DeploymentOption: WITHOUT_TRAFFIC_CONTROL
      DeploymentConfigName: CodeDeployDefault.OneAtATime
      OnPremisesInstanceTagFilters:
        - Key: Environment
          Value: !Ref DeploymentEnvironment
          Type: KEY_AND_VALUE
        - Key: Name
          Value: scup
          Type: KEY_AND_VALUE
      ServiceRoleArn: !GetAtt SUPCodeDeploySerivceRole.Arn

  SCUPCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: !Ref SCUPCodePipelineArtifactsBucket
        Type: S3
      Name: !Join ["-", [scup, codepipeline, !Ref DeployEnvironment]]
      PipelineType: V1
      RoleArn: !GetAtt SCUPCodePipelineServiceRole.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: GitHub
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: "1"
              OutputArtifacts:
                - Name: SCUPSourceCode
              Configuration:
                ConnectionArn: !Ref GitHubConnection
                FullRepositoryId: GDC-SOC/SCUP
                Branch: !Ref DeployEnvironment
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              InputArtifacts:
                - Name: SCUPSourceCode
        - Name: CloudFormation Deployment
          Actions:
            - Name: CloudFormation Deployment
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFromationStackSet
                Version: "1"
              Configuration:
                StackSetName: !Join ["-", [scup-, !Ref DeployEnvironment]]
                Description: Deploys the SCUP infrastructure CloudFormation template
                TemplatePath: 'SCUPSourceCode::deploy_scripts/scup-infrastructure.yaml'
              InputArtifacts:
                - Name: SCUPSourceCode
      Triggers:
        - ProviderType: CodeStarSourceConnection
          GitConfiguration:
            Push:
              Branches:
                Includes:
                  - *
      Tags:
        - Key: Environment
          Value: !Ref DeployEnvironment

  SCUPCodeDeploy:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: !Join ["-", [scup, codedeploy, !Ref DeployEnvironment]]
      ComputePlatform: Server

  SCUP:
    Type: AWS::Lightsail::Instance
    Properties:
      InstanceName: scup
      AvailabilityZone: us-east-1a
      BlueprintId: django_bitnami
      BundleId: small_3_0
      Networking:
        Ports:
          - CommonName: SSH
            Protocol: TCP
            FromPort: 22
            ToPort: 22
          - CommonName: HTTP
            Protocol: TCP
            FromPort: 80
            ToPort: 80
          - CommonName: HTTPS
            Protocol: TCP
            FromPort: 80
            ToPort: 80
      Tags:
        - Key: Environment
          Value: !Ref DeployEnvironment
        - Key: Name
          Value: scup

  # Nests the SCUP Lightsail instance CloudFormation template underneath the infrastructure
  # to allow it to be used both alone and through a full-infrastructure deploy
  # TODO not sure if this actually works the way I think it does
  SCUPInstance:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'SCUPSourceCode::deploy_scripts/scup-infrastructure.yaml'
      Parameters:
        DeployEnvironment: !Ref DeployEnvironment
