# Generated by Django 4.1.3 on 2023-04-11 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('blog', '0004_remove_blogpage_image_blogpage_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='blog_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
