name: Check 404 error

on:
  push:
    branches:
      - main # Change this to your primary branch if needed

jobs:
  test_redirect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run redirection test
        run: python .github/test_scripts/check_404.py